name: dsa_heldenverwaltung
description: "A DSA Hero Application"
publish_to: 'none'
version: 1.0.1+1

environment:
  sdk: ^3.10.4

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^3.3.1
  hive: ^2.2.3
  hive_flutter: ^1.1.0
  file_picker: ^11.0.1
  path: ^1.9.1
  path_provider: ^2.1.5
  share_plus: ^12.0.1
  uuid: ^4.5.1
  http: ^1.3.0
  firebase_core: ^4.6.0
  cloud_firestore: ^6.2.0
  firebase_auth: ^6.2.0
  encrypt: ^5.0.3
  pointycastle: ^3.9.1
  flutter_secure_storage: ^10.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  integration_test:
    sdk: flutter
  flutter_lints: ^6.0.0
  msix: ^3.16.8

msix_config:
  display_name: Heldenverwaltung
  publisher_display_name: Adamski
  identity_name: Adamski.Heldenverwaltung
  publisher: CN=1CE2B320-2BCD-4E40-9D73-3F57CE79C640
  msix_version: 1.2.1.0
  logo_path: assets/msix/heldenmanager_icon_500.png
  capabilities: internetClient
  languages: de-DE, en-US
  store: true

flutter:
  uses-material-design: true
  assets:
    - assets/catalogs/house_rules_v1/
    - assets/catalogs/house_rules_v1/packs/epic_rules_v1/manifest.json
    - assets/catalogs/house_rules_v1/packs/epic_rules_v1_advantages/manifest.json
    - assets/catalogs/house_rules_v1/packs/epic_rules_v1_combat_sf/manifest.json
    - assets/catalogs/house_rules_v1/packs/epic_rules_v1_disadvantages/manifest.json
    - assets/catalogs/house_rules_v1/packs/epic_rules_v1_general_sf/manifest.json
    - assets/catalogs/house_rules_v1/packs/epic_rules_v1_karmal_sf/manifest.json
    - assets/catalogs/house_rules_v1/packs/epic_rules_v1_liturgies/manifest.json
    - assets/catalogs/house_rules_v1/packs/epic_rules_v1_magic_sf/manifest.json
    - assets/catalogs/house_rules_v1/packs/epic_rules_v1_paths/manifest.json
    - assets/catalogs/house_rules_v1/packs/regelwerk_ueberarbeitung_v1/manifest.json
    - assets/catalogs/house_rules_v1/packs/regelwerk_ueberarbeitung_v1_combat/manifest.json
    - assets/catalogs/house_rules_v1/packs/regelwerk_ueberarbeitung_v1_economy/manifest.json
    - assets/catalogs/house_rules_v1/packs/regelwerk_ueberarbeitung_v1_general_sf/manifest.json
    - assets/catalogs/house_rules_v1/packs/regelwerk_ueberarbeitung_v1_karmal/manifest.json
    - assets/catalogs/house_rules_v1/packs/regelwerk_ueberarbeitung_v1_magic/manifest.json
    - assets/catalogs/house_rules_v1/packs/regelwerk_ueberarbeitung_v1_system/manifest.json
    - assets/catalogs/house_rules_v1/packs/regelwerk_ueberarbeitung_v1_talents_learning/manifest.json
    - assets/catalogs/reiseberichte/house_rules_v1/
    - assets/heroes/
    - assets/ui/codex/
  fonts:
    - family: Merriweather
      fonts:
        - asset: assets/fonts/merriweather/Merriweather.ttf
        - asset: assets/fonts/merriweather/Merriweather.ttf
          weight: 700
    - family: Cinzel
      fonts:
        - asset: assets/fonts/cinzel/Cinzel.ttf
        - asset: assets/fonts/cinzel/Cinzel.ttf
          weight: 700

