// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBp5GIbQkAAhEtrzh5uqq64GF8K94J_zvg',
    appId: '1:908461945796:web:677f0a2b7cde31063caa91',
    messagingSenderId: '908461945796',
    projectId: 'heldensync-ccf0b',
    authDomain: 'heldensync-ccf0b.firebaseapp.com',
    storageBucket: 'heldensync-ccf0b.firebasestorage.app',
    measurementId: 'G-NS3CXMLPXY',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOFkApTnA_2jtY6AXawRGAQJ3e28kedTk',
    appId: '1:908461945796:android:21be777f7afdff103caa91',
    messagingSenderId: '908461945796',
    projectId: 'heldensync-ccf0b',
    storageBucket: 'heldensync-ccf0b.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDNLk0kj-UgseEX-Q7p0MsaLYOsVQM6tUg',
    appId: '1:908461945796:ios:ee39c7a76a4720963caa91',
    messagingSenderId: '908461945796',
    projectId: 'heldensync-ccf0b',
    storageBucket: 'heldensync-ccf0b.firebasestorage.app',
    iosBundleId: 'de.adamski.heldenverwaltung',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDNLk0kj-UgseEX-Q7p0MsaLYOsVQM6tUg',
    appId: '1:908461945796:ios:ee39c7a76a4720963caa91',
    messagingSenderId: '908461945796',
    projectId: 'heldensync-ccf0b',
    storageBucket: 'heldensync-ccf0b.firebasestorage.app',
    iosBundleId: 'de.adamski.heldenverwaltung',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBp5GIbQkAAhEtrzh5uqq64GF8K94J_zvg',
    appId: '1:908461945796:web:bbd1b7e43d243e173caa91',
    messagingSenderId: '908461945796',
    projectId: 'heldensync-ccf0b',
    authDomain: 'heldensync-ccf0b.firebaseapp.com',
    storageBucket: 'heldensync-ccf0b.firebasestorage.app',
    measurementId: 'G-G85YKQKSQL',
  );
}
