import 'package:flutter_test/flutter_test.dart';

import 'package:dsa_heldenverwaltung/domain/hero_sheet.dart';
import 'package:dsa_heldenverwaltung/domain/hero_state.dart';
import 'package:dsa_heldenverwaltung/domain/wund_zustand.dart';
import 'package:dsa_heldenverwaltung/rules/derived/attribute_start_rules.dart';
import 'package:dsa_heldenverwaltung/state/hero_computed_snapshot.dart';

import '../test_support/hero_fixtures.dart';
import '../test_support/real_catalog.dart';

// Flache, lesbare Auswahl der Werte, die ein Nutzer am Helden sieht.
Map<String, Object?> _projektion(
  HeroSheet held,
  HeroState zustand,
  EchterKatalog katalog, {
  required bool epischeVorteile,
}) {
  final snapshot = buildHeroComputedSnapshot(
    hero: held,
    state: zustand,
    catalog: katalog.catalog,
    epicAdvantagesActive: epischeVorteile,
  );
  final basis = snapshot.derivedStats;
  final kampf = snapshot.combatPreviewStats;
  return <String, Object?>{
    'maxLep': basis.maxLep,
    'maxAu': basis.maxAu,
    'maxAsp': basis.maxAsp,
    'maxKap': basis.maxKap,
    'mr': basis.mr,
    'iniBase': basis.iniBase,
    'atBase': basis.atBase,
    'paBase': basis.paBase,
    'fkBase': basis.fkBase,
    'gs': basis.gs,
    'ausweichen': basis.ausweichen,
    'eigenschaften': snapshot.effectiveAttributes.toJson(),
    'startwerte': snapshot.effectiveStartAttributes.toJson(),
    'maxima': snapshot.attributeMaximums.toJson(),
    'wundschwelle': snapshot.wundschwelle,
    'wundProbenMalus': snapshot.wundEffekte.talentProbeMalus,
    'magie': snapshot.resourceActivation.magic.isEnabled,
    'karma': snapshot.resourceActivation.divine.isEnabled,
    'kampf': <String, Object?>{
      'rs': kampf.rsTotal,
      'be': kampf.beKampf,
      'at': kampf.at,
      'pa': kampf.pa,
      'ini': kampf.initiative,
      'ausweichen': kampf.ausweichen,
      'tp': kampf.tpExpression,
    },
    'hinweise': pendingAttributeTraitNotices(held),
  };
}

/// Erwartete Werte je Fall.
///
/// Aktualisieren nur im selben Commit wie eine gewollte Regel- oder
/// Kataloganpassung, mit Zeilenkommentar zum Grund; nie per Kopie der
/// Ist-Ausgabe. Waffenslots ohne TP/KK-Angabe (Schwelle 1) rechnen die volle
/// KK als TP-Bonus, wie die App es bei unvollständig gepflegten Waffen tut —
/// daher etwa `1W6+13` beim Magierstab von f02.
const Map<String, Map<String, Object?>> _erwartet =
    <String, Map<String, Object?>>{
      'f01_krieger_normal': <String, Object?>{
        'maxLep': 42,
        'maxAu': 48,
        'maxAsp': 33,
        'maxKap': 0,
        'mr': 5,
        'iniBase': 13,
        'atBase': 4,
        'paBase': 4,
        'fkBase': 1,
        'gs': 3,
        'ausweichen': 0,
        'eigenschaften': <String, Object?>{
          'mu': 15,
          'kl': 10,
          'inn': 12,
          'ch': 11,
          'ff': 11,
          'ge': 13,
          'ko': 14,
          'kk': 14,
        },
        'startwerte': <String, Object?>{
          'mu': 13,
          'kl': 10,
          'inn': 12,
          'ch': 11,
          'ff': 11,
          'ge': 12,
          'ko': 13,
          'kk': 14,
        },
        'maxima': <String, Object?>{
          'mu': 20,
          'kl': 15,
          'inn': 18,
          'ch': 17,
          'ff': 17,
          'ge': 18,
          'ko': 20,
          'kk': 21,
        },
        'wundschwelle': 7,
        'wundProbenMalus': -3,
        'magie': false,
        'karma': false,
        // Befund ARCH-07-B7: Die Armwunde (AT/PA −4) fehlt in AT/PA; die
        // Basiswerte oben und die Initiative enthalten sie.
        'kampf': <String, Object?>{
          'rs': 4,
          'be': 4,
          'at': 13,
          'pa': 12,
          'ini': 10,
          'ausweichen': 4,
          'tp': '1W6+4',
        },
        'hinweise': <String>[],
      },
      'f02_geode_magisch': <String, Object?>{
        'maxLep': 37,
        'maxAu': 46,
        'maxAsp': 46,
        'maxKap': 0,
        'mr': 10,
        'iniBase': 10,
        'atBase': 7,
        'paBase': 7,
        'fkBase': 8,
        'gs': 8,
        'ausweichen': 0,
        'eigenschaften': <String, Object?>{
          'mu': 12,
          'kl': 13,
          'inn': 14,
          'ch': 13,
          'ff': 12,
          'ge': 11,
          'ko': 13,
          'kk': 12,
        },
        'startwerte': <String, Object?>{
          'mu': 12,
          'kl': 13,
          'inn': 13,
          'ch': 12,
          'ff': 12,
          'ge': 11,
          'ko': 13,
          'kk': 12,
        },
        'maxima': <String, Object?>{
          'mu': 18,
          'kl': 20,
          'inn': 20,
          'ch': 18,
          'ff': 18,
          'ge': 17,
          'ko': 20,
          'kk': 18,
        },
        'wundschwelle': 6,
        'wundProbenMalus': 0,
        'magie': true,
        'karma': false,
        'kampf': <String, Object?>{
          'rs': 2,
          'be': 0,
          'at': 10,
          'pa': 9,
          'ini': 8,
          'ausweichen': 7,
          'tp': '1W6+13',
        },
        'hinweise': <String>[],
      },
      'f03_geweihter_karmal': <String, Object?>{
        'maxLep': 34,
        'maxAu': 40,
        'maxAsp': 32,
        'maxKap': 24,
        'mr': 3,
        'iniBase': 10,
        'atBase': 7,
        'paBase': 7,
        'fkBase': 8,
        'gs': 8,
        'ausweichen': 0,
        'eigenschaften': <String, Object?>{
          'mu': 12,
          'kl': 12,
          'inn': 14,
          'ch': 13,
          'ff': 13,
          'ge': 11,
          'ko': 12,
          'kk': 11,
        },
        'startwerte': <String, Object?>{
          'mu': 12,
          'kl': 12,
          'inn': 14,
          'ch': 13,
          'ff': 13,
          'ge': 11,
          'ko': 12,
          'kk': 11,
        },
        'maxima': <String, Object?>{
          'mu': 18,
          'kl': 18,
          'inn': 21,
          'ch': 20,
          'ff': 20,
          'ge': 17,
          'ko': 18,
          'kk': 17,
        },
        'wundschwelle': 6,
        'wundProbenMalus': 0,
        'magie': false,
        'karma': true,
        'kampf': <String, Object?>{
          'rs': 0,
          'be': 0,
          'at': 7,
          'pa': 7,
          'ini': 8,
          'ausweichen': 7,
          'tp': '1W6+11',
        },
        'hinweise': <String>[],
      },
      'f04_episch': <String, Object?>{
        'maxLep': 59,
        'maxAu': 79,
        'maxAsp': 67,
        'maxKap': 0,
        'mr': 5,
        'iniBase': 17,
        'atBase': 10,
        'paBase': 10,
        'fkBase': 9,
        'gs': 9,
        'ausweichen': 0,
        'eigenschaften': <String, Object?>{
          'mu': 17,
          'kl': 16,
          'inn': 15,
          'ch': 14,
          'ff': 14,
          'ge': 16,
          'ko': 18,
          'kk': 17,
        },
        'startwerte': <String, Object?>{
          'mu': 15,
          'kl': 14,
          'inn': 14,
          'ch': 13,
          'ff': 13,
          'ge': 14,
          'ko': 15,
          'kk': 15,
        },
        'maxima': <String, Object?>{
          'mu': 23,
          'kl': 21,
          'inn': 21,
          'ch': 20,
          'ff': 20,
          'ge': 22,
          'ko': 25,
          'kk': 25,
        },
        'wundschwelle': 9,
        'wundProbenMalus': 0,
        'magie': false,
        'karma': false,
        'kampf': <String, Object?>{
          'rs': 0,
          'be': 0,
          'at': 21,
          'pa': 19,
          'ini': 17,
          'ausweichen': 16,
          'tp': '1W6+5',
        },
        'hinweise': <String>[],
      },
      'f05_freitext_merkmale': <String, Object?>{
        'maxLep': 35,
        'maxAu': 38,
        'maxAsp': 28,
        'maxKap': 0,
        'mr': 3,
        // Befund ARCH-07-B1: INI +1 zählt doppelt (11 ohne Spiegelung).
        'iniBase': 12,
        'atBase': 7,
        'paBase': 7,
        'fkBase': 7,
        'gs': 8,
        'ausweichen': 0,
        'eigenschaften': <String, Object?>{
          'mu': 12,
          'kl': 12,
          'inn': 12,
          'ch': 12,
          'ff': 12,
          'ge': 12,
          'ko': 12,
          'kk': 12,
        },
        'startwerte': <String, Object?>{
          'mu': 12,
          'kl': 12,
          'inn': 12,
          'ch': 12,
          'ff': 12,
          'ge': 12,
          'ko': 12,
          'kk': 12,
        },
        'maxima': <String, Object?>{
          'mu': 18,
          'kl': 18,
          'inn': 18,
          'ch': 18,
          'ff': 18,
          'ge': 18,
          'ko': 18,
          'kk': 18,
        },
        'wundschwelle': 6,
        'wundProbenMalus': 0,
        'magie': false,
        'karma': false,
        'kampf': <String, Object?>{
          'rs': 0,
          'be': 0,
          'at': 7,
          'pa': 7,
          'ini': 10,
          'ausweichen': 7,
          'tp': '1W6+12',
        },
        'hinweise': <String>[],
      },
      'f06_gleichnamige_ausruestung': <String, Object?>{
        'maxLep': 23,
        'maxAu': 30,
        'maxAsp': 28,
        'maxKap': 0,
        'mr': 7,
        'iniBase': 11,
        'atBase': 8,
        'paBase': 8,
        'fkBase': 8,
        'gs': 6,
        'ausweichen': 0,
        'eigenschaften': <String, Object?>{
          'mu': 13,
          'kl': 11,
          'inn': 13,
          'ch': 10,
          'ff': 14,
          'ge': 14,
          'ko': 12,
          'kk': 12,
        },
        'startwerte': <String, Object?>{
          'mu': 13,
          'kl': 11,
          'inn': 13,
          'ch': 10,
          'ff': 14,
          'ge': 14,
          'ko': 12,
          'kk': 12,
        },
        'maxima': <String, Object?>{
          'mu': 20,
          'kl': 17,
          'inn': 20,
          'ch': 15,
          'ff': 21,
          'ge': 21,
          'ko': 18,
          'kk': 18,
        },
        'wundschwelle': 6,
        'wundProbenMalus': 0,
        'magie': false,
        'karma': false,
        'kampf': <String, Object?>{
          'rs': 2,
          'be': 2,
          'at': 13,
          'pa': 10,
          'ini': 8,
          'ausweichen': 6,
          'tp': '1W6+13',
        },
        'hinweise': <String>[],
      },
      'f07_legacy_schema1': <String, Object?>{
        // Befund ARCH-07-B1: LeP +2 zählt doppelt (34 ohne Spiegelung).
        'maxLep': 36,
        'maxAu': 32,
        'maxAsp': 20,
        'maxKap': 0,
        'mr': 3,
        // Befund ARCH-07-B1: INI +1 zählt doppelt.
        'iniBase': 16,
        'atBase': 8,
        'paBase': 8,
        'fkBase': 8,
        'gs': 8,
        'ausweichen': 0,
        'eigenschaften': <String, Object?>{
          'mu': 13,
          'kl': 11,
          'inn': 12,
          'ch': 10,
          'ff': 12,
          'ge': 13,
          'ko': 13,
          'kk': 14,
        },
        'startwerte': <String, Object?>{
          'mu': 13,
          'kl': 11,
          'inn': 12,
          'ch': 10,
          'ff': 12,
          'ge': 13,
          'ko': 13,
          'kk': 14,
        },
        'maxima': <String, Object?>{
          'mu': 20,
          'kl': 17,
          'inn': 18,
          'ch': 15,
          'ff': 18,
          'ge': 20,
          'ko': 20,
          'kk': 21,
        },
        'wundschwelle': 6,
        'wundProbenMalus': 0,
        'magie': false,
        'karma': false,
        'kampf': <String, Object?>{
          'rs': 0,
          'be': 0,
          'at': 13,
          'pa': 12,
          'ini': 13,
          'ausweichen': 8,
          'tp': '1W6+18',
        },
        'hinweise': <String>['KK +2'],
      },
      'f08_steigerungshistorie': <String, Object?>{
        'maxLep': 24,
        'maxAu': 31,
        'maxAsp': 31,
        'maxKap': 0,
        'mr': 7,
        'iniBase': 14,
        'atBase': 7,
        'paBase': 7,
        'fkBase': 7,
        'gs': 8,
        'ausweichen': 0,
        'eigenschaften': <String, Object?>{
          'mu': 13,
          'kl': 12,
          'inn': 13,
          'ch': 11,
          'ff': 12,
          'ge': 13,
          'ko': 12,
          'kk': 11,
        },
        'startwerte': <String, Object?>{
          'mu': 12,
          'kl': 12,
          'inn': 13,
          'ch': 11,
          'ff': 12,
          'ge': 13,
          'ko': 12,
          'kk': 11,
        },
        'maxima': <String, Object?>{
          'mu': 18,
          'kl': 18,
          'inn': 20,
          'ch': 17,
          'ff': 18,
          'ge': 20,
          'ko': 18,
          'kk': 17,
        },
        'wundschwelle': 6,
        'wundProbenMalus': 0,
        'magie': false,
        'karma': false,
        'kampf': <String, Object?>{
          'rs': 0,
          'be': 0,
          'at': 7,
          'pa': 7,
          'ini': 12,
          'ausweichen': 7,
          'tp': '1W6+11',
        },
        'hinweise': <String>[],
      },
      'f04_episch mit Brustwunde': <String, Object?>{
        'maxLep': 59,
        'maxAu': 79,
        'maxAsp': 67,
        'maxKap': 0,
        'mr': 5,
        'iniBase': 15,
        'atBase': 7,
        'paBase': 7,
        'fkBase': 6,
        'gs': 8,
        'ausweichen': 0,
        'eigenschaften': <String, Object?>{
          'mu': 17,
          'kl': 16,
          'inn': 15,
          'ch': 14,
          'ff': 14,
          'ge': 16,
          'ko': 18,
          'kk': 17,
        },
        'startwerte': <String, Object?>{
          'mu': 15,
          'kl': 14,
          'inn': 14,
          'ch': 13,
          'ff': 13,
          'ge': 14,
          'ko': 15,
          'kk': 15,
        },
        'maxima': <String, Object?>{
          'mu': 23,
          'kl': 21,
          'inn': 21,
          'ch': 20,
          'ff': 20,
          'ge': 22,
          'ko': 25,
          'kk': 25,
        },
        'wundschwelle': 9,
        'wundProbenMalus': -1,
        'magie': false,
        'karma': false,
        // Befund ARCH-07-B7: AT/PA bleiben wie ohne Wunde, die AT-Basis sinkt.
        'kampf': <String, Object?>{
          'rs': 0,
          'be': 0,
          'at': 21,
          'pa': 19,
          'ini': 15,
          'ausweichen': 16,
          'tp': '1W6+5',
        },
        'hinweise': <String>[],
      },
      'f04_episch mit Brustwunde ohne epische Vorteile': <String, Object?>{
        'maxLep': 59,
        'maxAu': 79,
        'maxAsp': 67,
        'maxKap': 0,
        'mr': 5,
        'iniBase': 15,
        'atBase': 7,
        'paBase': 7,
        'fkBase': 6,
        'gs': 8,
        'ausweichen': 0,
        'eigenschaften': <String, Object?>{
          'mu': 17,
          'kl': 16,
          'inn': 15,
          'ch': 14,
          'ff': 14,
          'ge': 16,
          'ko': 18,
          'kk': 17,
        },
        'startwerte': <String, Object?>{
          'mu': 15,
          'kl': 14,
          'inn': 14,
          'ch': 13,
          'ff': 13,
          'ge': 14,
          'ko': 15,
          'kk': 15,
        },
        'maxima': <String, Object?>{
          'mu': 23,
          'kl': 21,
          'inn': 21,
          'ch': 20,
          'ff': 20,
          'ge': 22,
          'ko': 25,
          'kk': 25,
        },
        'wundschwelle': 9,
        'wundProbenMalus': -3,
        'magie': false,
        'karma': false,
        // Befund ARCH-07-B7: wie oben.
        'kampf': <String, Object?>{
          'rs': 0,
          'be': 0,
          'at': 21,
          'pa': 19,
          'ini': 15,
          'ausweichen': 16,
          'tp': '1W6+5',
        },
        'hinweise': <String>[],
      },
    };

void main() {
  TestWidgetsFlutterBinding.ensureInitialized();

  late EchterKatalog katalog;

  setUpAll(() async {
    katalog = await ladeEchtenRegelkatalog();
  });

  void pruefe(
    String name,
    Bestandsheld held, {
    required bool episch,
    WundZustand? wunden,
  }) {
    test(name, () {
      final bundle = ladeBestandsheld(held);
      final zustand = wunden == null
          ? bundle.state
          : bundle.state.copyWith(wpiZustand: wunden);
      final ist = _projektion(
        bundle.hero,
        zustand,
        katalog,
        epischeVorteile: episch,
      );
      expect(ist, _erwartet[name]);
    });
  }

  test('alle eingebauten Hausregel-Pakete sind aktiv', () {
    expect(katalog.epicAdvantagesActive, isTrue);
  });

  for (final held in Bestandsheld.values) {
    pruefe(held.datei, held, episch: true);
  }

  // KO ist bei f04 Haupteigenschaft: Mit dem Hausregel-Paket fuer epische
  // Vorteile halbiert sich die Wund-Probenerschwernis, ohne es nicht.
  const brustwunde = WundZustand(wundenProZone: {WundZone.brust: 1});
  pruefe(
    '${Bestandsheld.episch.datei} mit Brustwunde',
    Bestandsheld.episch,
    episch: true,
    wunden: brustwunde,
  );
  pruefe(
    '${Bestandsheld.episch.datei} mit Brustwunde ohne epische Vorteile',
    Bestandsheld.episch,
    episch: false,
    wunden: brustwunde,
  );
}
